/**
 * Forecast endpoint — serves pre-computed flavor predictions from KV.
 *
 * Forecasts are generated by the Python batch job (analytics/batch_forecast.py)
 * and stored in KV as JSON under `forecast:{slug}`.
 *
 * GET /api/v1/forecast/{slug}
 *   → { store_slug, date, predictions: [{flavor, probability}], prose }
 */

/**
 * Handle forecast route.
 * @param {string} slug - Store slug from URL path
 * @param {Object} env - Worker env bindings
 * @param {Object} corsHeaders
 * @returns {Promise<Response>}
 */
export async function handleForecast(slug, env, corsHeaders) {
  const kv = env.FLAVOR_CACHE;
  if (!kv) {
    return Response.json(
      { error: 'Forecast data not available — KV not configured' },
      { status: 503, headers: corsHeaders },
    );
  }

  // Check for pre-computed forecast in KV
  const forecastKey = `forecast:${slug}`;
  const cached = await kv.get(forecastKey);

  if (!cached) {
    return Response.json(
      { error: `No forecast available for "${slug}". Forecasts are generated daily by the batch pipeline.` },
      { status: 404, headers: corsHeaders },
    );
  }

  try {
    const forecast = JSON.parse(cached);
    return Response.json(forecast, {
      headers: {
        ...corsHeaders,
        'Cache-Control': 'public, max-age=3600', // 1 hour
      },
    });
  } catch {
    return Response.json(
      { error: 'Forecast data corrupted' },
      { status: 500, headers: corsHeaders },
    );
  }
}
